### ISSUE TITLE
Modernization

### ISSUE THREAD

**Issue by ml0130** [Houston-ARTCC/zhu-core#2]
Don't get me wrong there's a lot of good that our current site has to go for it compared to where it was last year. But I have seen several centers that have a bot on their teamspeak and/or discord that's tied to the website to help manage both tags and names. Why haven't we moved there yet? I do understand at least for the teamspeak side of things that's hard to do since we don't "own" the server, But for discord why don't we have at least that?

**Comment by MikeRomaa** [comment]
This has been handled by the VATUSA bot for a while now. Closing.
